import {
  Target,
  TrendingUp,
  TrendingDown,
  Wallet,
  ShoppingBag,
  Coffee,
  Car,
  Home as HomeIcon,
  Heart,
  Utensils,
  Gamepad2,
  Dumbbell,
  GraduationCap,
  Plane,
  Gift,
  Smartphone,
  Zap,
  Droplets,
  Tv,
  Briefcase,
  Music,
  ShoppingCart
} from "lucide-react-native";

export const ICON_LIST = [
  { name: "Target", lib: Target },
  { name: "TrendingUp", lib: TrendingUp },
  { name: "TrendingDown", lib: TrendingDown },
  { name: "Wallet", lib: Wallet },
  { name: "ShoppingBag", lib: ShoppingBag },
  { name: "Coffee", lib: Coffee },
  { name: "Utensils", lib: Utensils },
  { name: "Car", lib: Car },
  { name: "Home", lib: HomeIcon },
  { name: "Heart", lib: Heart },
  { name: "Gamepad2", lib: Gamepad2 },
  { name: "Dumbbell", lib: Dumbbell },
  { name: "GraduationCap", lib: GraduationCap },
  { name: "Plane", lib: Plane },
  { name: "Gift", lib: Gift },
  { name: "Smartphone", lib: Smartphone },
  { name: "Zap", lib: Zap },
  { name: "Droplets", lib: Droplets },
  { name: "Tv", lib: Tv },
  { name: "Briefcase", lib: Briefcase },
  { name: "Music", lib: Music },
  { name: "ShoppingCart", lib: ShoppingCart },
];

export const PRESET_COLORS = [
  "#00F5FF",
  "#FF00E5",
  "#00FF85",
  "#A020F0",
  "#FFB800",
  "#FF5252",
  "#FFFFFF",
  "#8B4513",
  "#F50",
  "#4CC9F0",
  "#4895EF",
  "#7209B7",
  "#B5179E",
  "#F72585",
  "#F9C74F",
  "#90BE6D",
  "#43AA8B",
  "#577590",
  "#BC6C25",
  "#DDA15E",
  "#606C38",
];